### ISSUE TITLE
Support for nested messages

### ISSUE THREAD

**Issue by jimmywan** [kinow/protobuf-uml-diagram#1]
This doesn't appear to work on my web of protobufs that includes nested messages.

```proto
message FieldInfo {
    optional string name = 1;

    message IntegerStats {
        repeated double percentile = 5;
    }
}
```

**Comment by kinow** [comment]
Sorry for the delay. Have just got back from overseas, will give it a try in the next days. Thanks for trying to use it!

**Comment by kinow** [comment]
Confirmed issue, by creating `bruno.proto` with

```
syntax = "proto3";

message FieldInfo {
    string name = 1;

    message IntegerStats {
        repeated double percentile = 5;
    }
}
```

(removed the `optional` to fix proto3 warning)

Then compiling with 

```
$ protoc bruno.proto --python_out=.
```

And generating diagram with: `PYTHONPATH=. protobuf-uml-diagram --proto "bruno_pb2" --output /tmp`

The generated diagram does not include the `IntegerStats`.

![bruno_pb2](https://user-images.githubusercontent.com/304786/60765562-94c45200-a0f0-11e9-8464-d13feeaa6d82.png)

**Comment by kinow** [comment]
UML template generated: 

```

        digraph "Protobuf UML class diagram" {
            fontname = "Bitstream Vera Sans"
            fontsize = 8

            node [
                fontname = "Bitstream Vera Sans"
                fontsize = 8
                shape = "record"
                style=filled
                fillcolor=gray95
            ]

            edge [
                fontname = "Bitstream Vera Sans"
                fontsize = 8

            ]

        2[label = "{FieldInfo|+ name:string}"]


    
        }
        
```

**Comment by kinow** [comment]
@jimmywan I think I know one way to implement it. Do you have a more complex example, where you actually used this recursion, or how you used it?

I am concerned in implementing that myself and missing some case you may have.

**Comment by jimmywan** [comment]
@kinow Sorry for the delay in responding. Forgot about this after the holiday.

My definitions looks something like this except that FieldType and FieldInfo are in different packages.
```proto
enum FieldType {
    TYPE_UNKNOWN = 0;
    INTEGER = 1;
    REAL_NUMBER = 2;
    CATEGORICAL = 3;
    DATE = 4;
    TEXT = 5;
}

message FieldInfo {
    optional string name = 1;
    optional FieldType type = 2;
    optional int32 empty_count = 4;
    optional int32 count = 5;

    message IntegerStats {
        optional int64 min = 1;
        optional int64 max = 2;
        optional int64 mean = 3;
        optional int64 median = 4;
        repeated double percentile = 5;
    }
    message RealNumberStats {
        optional double min = 1;
        optional double max = 2;
        optional double mean = 3;
        optional double median = 4;
        repeated double percentile = 5;
    }
    message DateStats {
        optional string min = 1;
        optional string max = 2;
        optional string mean = 3;
        repeated string percentile = 5;
    }
    message CategoricalStats {
        optional int32 unique = 1;
        optional string most_frequent = 2;
    }
    oneof stats {
      IntegerStats integer_stats = 100;
      RealNumberStats real_number_stats = 101;
      DateStats date_stats = 102;
      CategoricalStats categorical_stats = 103;
    }
}
```

**Comment by kinow** [comment]
Excellent @jimmywan . I used this example with my current local change, and got a `KeyError` due to a bug. Already saved us some time :) will keep fixing it locally until I have this example working and then prepare a PR.

Thanks

**Comment by kinow** [comment]
![nested_pb2](https://user-images.githubusercontent.com/304786/65830028-3fbb6500-e308-11e9-8267-935fab258ae8.png)

Here's the generated diagram with the latest code (tagged 0.2).

Let me know if that works @jimmywan ! If not, just re-open the issue or create a new one if there are any other issues.

Cheers
Bruno
